In [12]:
import pandas as pd

In [13]:
accepted = pd.read_csv('accepted_2007_to_2018Q4.csv')

/Users/jameskim/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [14]:
sample = accepted.sample(10000)

In [15]:
sample = sample.iloc[:,81:121]

In [16]:
sample.head()

,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,...,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc
107788,58.4,0.0,0.0,84.0,96.0,13.0,13.0,0.0,17.0,NaN,...,58007.0,47449.0,10000.0,44907.0,NaN,NaN,NaN,NaN,NaN,NaN
324573,96.7,0.0,0.0,133.0,164.0,7.0,7.0,4.0,7.0,NaN,...,225100.0,27635.0,12600.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1957695,68.1,0.0,0.0,162.0,297.0,52.0,22.0,4.0,189.0,NaN,...,193824.0,51054.0,28100.0,57424.0,NaN,NaN,NaN,NaN,NaN,NaN
2035474,75.7,0.0,0.0,60.0,66.0,3.0,3.0,0.0,66.0,NaN,...,59400.0,48116.0,9500.0,31900.0,NaN,NaN,NaN,NaN,NaN,NaN
2002146,79.6,0.0,0.0,50.0,21.0,6.0,6.0,0.0,6.0,NaN,...,50537.0,44698.0,4600.0,39937.0,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#checking to see what columns has at least 1 missing values.
#all of them have at least 1 missing value
sample.columns[sample.isna().any()].tolist()

['bc_util',
 'chargeoff_within_12_mths',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc']

In [18]:
len(sample.columns[sample.isna().any()].tolist())

39

In [19]:
#looking for which row has all missing value
#dropping this row
idx = sample.index[sample.isnull().all(1)]
nans = sample.ix[idx]
nans

/Users/jameskim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

Empty DataFrame
Columns: [bc_util, chargeoff_within_12_mths, delinq_amnt, mo_sin_old_il_acct, mo_sin_old_rev_tl_op, mo_sin_rcnt_rev_tl_op, mo_sin_rcnt_tl, mort_acc, mths_since_recent_bc, mths_since_recent_bc_dlq, mths_since_recent_inq, mths_since_recent_revol_delinq, num_accts_ever_120_pd, num_actv_bc_tl, num_actv_rev_tl, num_bc_sats, num_bc_tl, num_il_tl, num_op_rev_tl, num_rev_accts, num_rev_tl_bal_gt_0, num_sats, num_tl_120dpd_2m, num_tl_30dpd, num_tl_90g_dpd_24m, num_tl_op_past_12m, pct_tl_nvr_dlq, percent_bc_gt_75, pub_rec_bankruptcies, tax_liens, tot_hi_cred_lim, total_bal_ex_mort, total_bc_limit, total_il_high_credit_limit, revol_bal_joint, sec_app_fico_range_low, sec_app_fico_range_high, sec_app_earliest_cr_line, sec_app_inq_last_6mths, sec_app_mort_acc]
Index: []

[0 rows x 40 columns]

In [20]:
#dropping all columns where missingness accounts for 95%+ of the column
sample.isna().sum()

bc_util                            332
chargeoff_within_12_mths             2
delinq_amnt                          0
mo_sin_old_il_acct                 605
mo_sin_old_rev_tl_op               308
mo_sin_rcnt_rev_tl_op              308
mo_sin_rcnt_tl                     308
mort_acc                           229
mths_since_recent_bc               321
mths_since_recent_bc_dlq          7663
mths_since_recent_inq             1344
mths_since_recent_revol_delinq    6682
num_accts_ever_120_pd              308
num_actv_bc_tl                     308
num_actv_rev_tl                    308
num_bc_sats                        261
num_bc_tl                          308
num_il_tl                          308
num_op_rev_tl                      308
num_rev_accts                      308
num_rev_tl_bal_gt_0                308
num_sats                           261
num_tl_120dpd_2m                   679
num_tl_30dpd                       308
num_tl_90g_dpd_24m                 308
num_tl_op_past_12m                 308
pct_tl_nvr_dlq                     310
percent_bc_gt_75                   326
pub_rec_bankruptcies                 6
tax_liens                            1
tot_hi_cred_lim                    308
total_bal_ex_mort                  229
total_bc_limit                     229
total_il_high_credit_limit         308
revol_bal_joint                   9534
sec_app_fico_range_low            9534
sec_app_fico_range_high           9534
sec_app_earliest_cr_line          9534
sec_app_inq_last_6mths            9534
sec_app_mort_acc                  9534
dtype: int64

In [21]:
#columns to drop
sample.drop(['revol_bal_joint', 'sec_app_fico_range_low','sec_app_fico_range_high','sec_app_earliest_cr_line','sec_app_inq_last_6mths'
             ,'sec_app_mort_acc'], axis=1, inplace=True)

In [22]:
sample.sample(20)

,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
142547,92.0,0.0,0.0,28.0,110.0,4.0,4.0,0.0,4.0,NaN,...,0.0,2.0,100.0,83.3,0.0,0.0,79280.0,58222.0,33000.0,33280.0
1677165,85.9,0.0,0.0,188.0,124.0,2.0,2.0,1.0,58.0,NaN,...,0.0,7.0,95.3,100.0,1.0,0.0,313093.0,8052.0,4600.0,4200.0
1665707,55.2,0.0,0.0,15.0,135.0,6.0,6.0,0.0,6.0,NaN,...,0.0,1.0,92.9,0.0,0.0,0.0,37629.0,26535.0,17100.0,20529.0
1302003,97.1,0.0,0.0,139.0,181.0,40.0,5.0,7.0,40.0,NaN,...,0.0,1.0,95.3,100.0,0.0,0.0,281642.0,81837.0,19900.0,96558.0
1357509,74.8,0.0,0.0,NaN,50.0,12.0,12.0,0.0,32.0,NaN,...,0.0,2.0,100.0,50.0,0.0,0.0,10800.0,6455.0,7300.0,0.0
545205,94.3,0.0,0.0,127.0,138.0,16.0,9.0,0.0,16.0,NaN,...,0.0,1.0,92.9,100.0,0.0,0.0,58146.0,35890.0,21400.0,29146.0
1182619,79.6,0.0,0.0,152.0,144.0,1.0,1.0,6.0,1.0,NaN,...,0.0,5.0,94.4,75.0,0.0,0.0,310910.0,80477.0,11700.0,75933.0
1890867,75.4,0.0,0.0,7.0,153.0,12.0,7.0,1.0,17.0,88.0,...,0.0,2.0,100.0,66.7,0.0,0.0,272757.0,23499.0,3200.0,16695.0
597114,99.1,0.0,0.0,138.0,317.0,11.0,11.0,0.0,11.0,NaN,...,0.0,1.0,100.0,100.0,1.0,0.0,25900.0,18765.0,12500.0,9000.0
1888396,90.2,0.0,0.0,160.0,169.0,12.0,12.0,0.0,23.0,NaN,...,0.0,1.0,94.0,80.0,0.0,0.0,72286.0,60593.0,8700.0,23595.0
609292,55.5,0.0,0.0,147.0,211.0,6.0,6.0,0.0,6.0,NaN,...,0.0,2.0,100.0,25.0,0.0,0.0,42020.0,20896.0,32300.0,9720.0
2049942,81.6,0.0,0.0,142.0,161.0,13.0,13.0,1.0,80.0,NaN,...,0.0,0.0,96.4,100.0,0.0,0.0,169220.0,26118.0,10200.0,38780.0
705495,71.4,0.0,0.0,158.0,150.0,50.0,6.0,0.0,53.0,30.0,...,1.0,1.0,88.5,50.0,0.0,0.0,14300.0,10933.0,5200.0,5000.0
1153253,72.2,0.0,0.0,156.0,149.0,20.0,20.0,0.0,20.0,37.0,...,0.0,0.0,84.0,66.7,0.0,0.0,101852.0,76680.0,4300.0,97552.0
2234229,72.9,0.0,0.0,37.0,269.0,21.0,21.0,0.0,21.0,NaN,...,0.0,0.0,100.0,66.7,1.0,0.0,48674.0,26181.0,29600.0,4500.0
1634509,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
574493,76.4,0.0,0.0,136.0,140.0,20.0,15.0,1.0,25.0,NaN,...,0.0,0.0,81.8,100.0,0.0,0.0,106922.0,17538.0,3500.0,17251.0
1178072,60.1,0.0,0.0,94.0,89.0,4.0,4.0,0.0,4.0,NaN,...,0.0,2.0,100.0,28.6,0.0,0.0,21300.0,12807.0,21300.0,0.0
1226764,62.8,0.0,0.0,97.0,174.0,2.0,2.0,2.0,35.0,NaN,...,0.0,2.0,92.0,20.0,0.0,0.0,41500.0,28655.0,15100.0,16000.0
874032,92.1,0.0,0.0,85.0,133.0,36.0,7.0,2.0,36.0,NaN,...,0.0,2.0,96.3,100.0,0.0,0.0,264700.0,9889.0,1500.0,6500.0

In [23]:
#columns to fillna with 0
fill = sample[['bc_util','chargeoff_within_12_mths',
                'delinq_amnt','mort_acc','mths_since_recent_bc','mths_since_recent_bc_dlq',
                 'num_tl_90g_dpd_24m','num_tl_op_past_12m','pub_rec_bankruptcies','tax_liens']]

In [24]:
for column in fill:
    sample[column].fillna(0)

In [25]:
sample = sample.fillna(-999)

In [26]:
sample.isna().sum()

bc_util                           0
chargeoff_within_12_mths          0
delinq_amnt                       0
mo_sin_old_il_acct                0
mo_sin_old_rev_tl_op              0
mo_sin_rcnt_rev_tl_op             0
mo_sin_rcnt_tl                    0
mort_acc                          0
mths_since_recent_bc              0
mths_since_recent_bc_dlq          0
mths_since_recent_inq             0
mths_since_recent_revol_delinq    0
num_accts_ever_120_pd             0
num_actv_bc_tl                    0
num_actv_rev_tl                   0
num_bc_sats                       0
num_bc_tl                         0
num_il_tl                         0
num_op_rev_tl                     0
num_rev_accts                     0
num_rev_tl_bal_gt_0               0
num_sats                          0
num_tl_120dpd_2m                  0
num_tl_30dpd                      0
num_tl_90g_dpd_24m                0
num_tl_op_past_12m                0
pct_tl_nvr_dlq                    0
percent_bc_gt_75                  0
pub_rec_bankruptcies              0
tax_liens                         0
tot_hi_cred_lim                   0
total_bal_ex_mort                 0
total_bc_limit                    0
total_il_high_credit_limit        0
dtype: int64